### ISSUE TITLE
Does termux-adb works in non rooted android.

### ISSUE THREAD

**Issue by kcubeterm** [MasterDevX/Termux-ADB#11]
I installed it ,but i dont seems ,it's works same like pc version.

**Comment by Sohil876** [comment]
I dont think it works without root, didnt for me.

**Comment by kcubeterm** [comment]
I will have to fork  and do change in my free time,then maybe it will work,

**Comment by MasterDevX** [comment]
@kcubeterm @Sohil876 This project should run on both rooted and non-rooted devices. If you have any issues with Termux-ADB, try to explain what are you trying to do and what error are you getting, thanks.

**Comment by kcubeterm** [comment]
Sound nice , thanks @MasterDevX

**Comment by MasterDevX** [comment]
Closing for now, feel free to reopen this or open a new issue if you get any troubles, thanks!

**Comment by Sohil876** [comment]
> @kcubeterm @Sohil876 This project should run on both rooted and non-rooted devices. If you have any issues with Termux-ADB, try to explain what are you trying to do and what error are you getting, thanks.

It didn't recognise any device unless i was root, it was on my tab lenovo tab 2 a-30hc, android marshmallow, i no longer have the tab so can't test unfortunately.

**Comment by kcubeterm** [comment]
First of all , make sure your device connected with usb, then try, May be it worked. Since i can't try because, my second phone run on android 4.0 , that's too bad

**Comment by MasterDevX** [comment]
@kcubeterm @Sohil876 You probably should not try to connect devices via USB, because most devices' kernels most likely won't recogize plugged device as ADB device and will try to mount it as simple USB flash storage. Yep, you can try, of course, but connecting ADB devices by this way seems not to work in most cases. Try to use "ADB Over Network" instead. If your device is running Android 5+ you can enable this option in developer settings, then in Termux where you have already installed ADB execute ```adb connect ip```, don't forget to replace ```ip``` with your target device's local IP adress. For example, this command for me looks like this: ```adb connect 192.168.0.120```. If you are on Android < 5, you need a PC to enable "ADB Over Network". To do so, connect your device to PC with ADB installed there using USB and run command on your PC: ```adb tcpip 5555```.

**Comment by Sohil876** [comment]
> First of all , make sure your device connected with usb, then try, May be it worked. Since i can't try because, my second phone run on android 4.0 , that's too bad

I remember i didnt actually unplugged the cable at all and tried on user mode connecting didnt work, did a su and tried as root, worked. Yeah now that i think about it i couldve done adb wireless too didnt cross my mind.

**Comment by Sohil876** [comment]
> @kcubeterm @Sohil876 You probably should not try to connect devices via USB, because most devices' kernels most likely won't recogize plugged device as ADB device and will try to mount it as simple USB flash storage. Yep, you can try, of course, but connecting ADB devices by this way seems not to work in most cases. Try to use "ADB Over Network" instead. If your device is running Android 5+ you can enable this option in developer settings, then in Termux where you have already installed ADB execute `adb connect ip`, don't forget to replace `ip` with your target device's local IP adress. For example, this command for me looks like this: `adb connect 192.168.0.120`. If you are on Android < 5, you need a PC to enable "ADB Over Network". To do so, connect your device to PC with ADB installed there using USB and run command on your PC: `adb tcpip 5555`.

Hmm makes sense, but if thats the case why would it recognize the device if i ran adb as root though?
