### ISSUE TITLE
Transport ID?

### ISSUE THREAD

**Issue by JASHUV** [MasterDevX/Termux-ADB#15]
![Screenshot_2020-03-22-09-24-38-958_com termux](https://user-images.githubusercontent.com/24798843/77241964-a1a5b900-6c1f-11ea-91c2-b67976857fe8.jpg)

**Comment by MasterDevX** [comment]
I think this is happening because of the ADB binaries used here are a bit outdated.
So the way to solve this is probably to build new binaries from Google's source, what is already in my ToDo list. I currently don't have enough free time to build them, so if you want you can try compiling it yourself :smile:
